version: '3'

services:
  web:
    build: ./app
    command: gunicorn bookmarks.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: